### ISSUE TITLE
IOWindow test in allocore failing

### ISSUE THREAD

**Issue by mantaraya36** [AlloSphere-Research-Group/AlloSystem#51]
The IOWindow test from the Allocore test suite is failing for me with:
```
allocoreTests: /home/andres/Documents/src/Allostuff/AlloSystem-github/allocore/unitTests/utIOWindowGL.cpp:38: virtual bool MyWindow::onResize(int, int): Assertion `onCreateCalls' failed.
```
The test code looks like:
```

	bool onResize(int dw, int dh){
		assert(onCreateCalls);	// at least one onCreate called
		if(onCreateCalls == 1){
			assert(dw == dimensions().w);
			assert(dh == dimensions().h);
		}
		++onResizeCalls;
		return true;
	}
```

**Comment by mantaraya36** [comment]
Removing the line:
```
assert(onCreateCalls);  // at least one onCreate called
```

Fixes the issue, but it seems that the fix should be deeper and more complex.

**Comment by LancePutnam** [comment]
Seems like the onCreate call got accidentally moved to after onResize when I refactored Window. I just fixed this (https://github.com/AlloSphere-Research-Group/AlloSystem/commit/40ae94de0dbcbdd2c0ebe4ad037b7d475dff083c) so hopefully the test passes now.

**Comment by mantaraya36** [comment]
Fixed for me. Travis build is still failing allocoreTest, but this issue is resolved.
