### ISSUE TITLE
AudioIO: cannot create virtual channels

### ISSUE THREAD

**Issue by LancePutnam** [AlloSphere-Research-Group/AlloSystem#54]
In the latest devel, one can no longer create virtual channels with AudioIO. The code has changed to only create the min of the requested channels and max device channels. I updated the AudioIO unit test to illustrate the problem:

https://github.com/AlloSphere-Research-Group/AlloSystem/commit/dc5ec79a3f2175553812f0000d9a54a96618a365

**Comment by mantaraya36** [comment]
Test now passes. Can you explain what this feature could be used for?

**Comment by grrrwaaa** [comment]
One example we used it for was the ambisonic domain signals. Kind of like a multi-pass render: the encoders sum into the virtual channels, the decoders read from these and multiplex into the real output channels. Respective channel counts can be quite different.

Another is to test code for > 2 channels when running about with just a laptop.

Graham


Graham Wakefield
Assistant Professor, Canada Research Chair (Tier II), Digital Media, Visual Art & Art History, 
York University, 303C, Goldfarb Center for Fine Arts, 4700 Keele Street, Toronto ON, Canada
1 416 400 7421
www.grahamwakefield.net
www.artificialnature.net

**Comment by LancePutnam** [comment]
Yes, good examples Graham. The initial reason I implemented them was the latter---running Allosphere code on a laptop without all kinds of channel count checks and separate code paths. You can still check the number of device channels opened if you want to do all that stuff...

**Comment by mantaraya36** [comment]
Thanks for the ideas. It makes perfect sense.
